server:
  port: 8081
eureka:
  client:
    register-with-eureka: false # 不需要向Eureka注册自己
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
#Eureka

#开启降级feign、hystrix
feign:
  hystrix:
    enabled: true